### ISSUE TITLE
Brightness not changing

### ISSUE THREAD

**Issue by mordax7** [cyrinux/wluma-als-emulator#4]
Hello.

I was trying to use it but it does not automatically adjusts screen brightness. I installed `wluma-als-emulator-git` and all dependencies.(As far as I could see)

Here the output:
```
❯ wluma-als-emulator --verbose
Sleep mode: lux will be use
input: /dev/video0, output: /tmp/fake-devices/light-sensor/in_illuminance_raw
lux=27 | waiting 30 seconds...
lux=31 | waiting 30 seconds...
lux=31 | waiting 30 seconds...
lux=26 | waiting 30 seconds...
```

Am I missing something?

**Comment by cyrinux** [comment]
Hi, do you also install and start wluma?

Mar 30, 2021 00:29:42 Aljaž Gantar ***@***.***>:

**Comment by mordax7** [comment]
Ah, ok, I did not know `wluma` has to be started manually. Do I have to start `wluma` or `als-emulator` with any specific argument?

**Comment by cyrinux** [comment]
You need 
```
$ cat ~/.config/wluma/service.conf
WLUMA_AMBIENT_LIGHT_SENSOR_BASE_PATH=/tmp/fake-devices
```

Then `systemctl enable --now wluma` .

It will like this read this fake light sensor in you like me doesnt got an hardware light sensor.

**Comment by max-baz** [comment]
I'll hijack the thread ( 😛 ) and just say, do share the feedback, it's very welcome 😉 I'm in a (very very slow) process of rewriting `wluma` in rust, because C code is really hard and boring for me to maintain and work on - the new version will contain some version of this project inside, i.e. will work even if you don't have a light sensor.

**Comment by cyrinux** [comment]
Now you announce it publicly, you must code! 😁

**Comment by mordax7** [comment]
@cyrinux still no success  :worried: 

What I tried:
Exactly the way you described it, and...

First terminal running:
```
~
❯ set WLUMA_AMBIENT_LIGHT_SENSOR_BASE_PATH /tmp/fake-devices

~ 
❯ wluma
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```
Second terminal running:
```
❯ wluma-als-emulator --strategy=webcam --verbose
Sleep mode: lux will be use
input: /dev/video0, output: /tmp/fake-devices/light-sensor/in_illuminance_raw
lux=17 | waiting 30 seconds...
lux=27 | waiting 30 seconds...
lux=27 | waiting 30 seconds...
lux=21 | waiting 30 seconds...
lux=17 | waiting 30 seconds...
```

Both did not work. Am I missing something?

@maximbaz hehe :smile: happy to see you here!
* Well, from the first glance, having a workaround for the people without a light sensor already build in `woluma`, would be a significant improvement.
* Otherwise, some more logging options would be excellent. Right now, I don't see much output than the `MESA-INTEL` warning. 
* What I am super eager to find out right now is also if it changes the external monitor's brightness? I saw it should be possible with `xrandr`, but wanted to know if `woluma` can do it too. :slightly_smiling_face:

**Comment by max-baz** [comment]
> Both did not work. Am I missing something?

I think you might be missing the fact that you have to train the model! 😁 go to white screen (e.g. open google), decrease your brightness by hand, then open something dark (vscode) and increase your brightness, then go back and forth between google and vscode and observe the magic!

> What I am super eager to find out right now is also if it changes the external monitor's brightness? 

Not right now, but this is another feature that is definitely wanted (and was already requested by @cyrinux haha) - managing external screen brightness is done with `ddcutil` tool (remember wluma is wayland / wlroots specific, so Xorg stuff like `xrandr` won't help you). 

But duly noted all the points 😉

**Comment by mordax7** [comment]
> I think you might be missing the fact that you have to train the model! grin go to white screen (e.g. open google), decrease your brightness by hand, then open something dark (vscode) and increase your brightness, then go back and forth between google and vscode and observe the magic!

Ahh yes, had to play around with the brightness level :+1:

Thanks you both @cyrinux and @maximbaz  for your help! :slightly_smiling_face: 

Closing this one!
